---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:05
---程序主入口，以及love2d相关的生命周期回调

require('app/approot')

---@type AppRoot
AppRoot = classLib.AppRoot.new()

local loveGraphics = love.graphics
local loveTimer = love.timer
local spendTimeTips = {'Rendering Time: ',0}
local resolutionTips = table.concat({'Resolution: ',PIXEL_WIDTH,' x ',PIXEL_HEIGHT},'')

local function start()
    love.window.setTitle("使用Lua基于Love2D引擎实现3d渲染管线")
    love.window.setMode(SCREEN_WIDTH, SCREEN_HEIGHT, {resizable=false, vsync=false})
    love.filesystem.setSymlinksEnabled(true)
    AppRoot:Init()
end

function love.load()
    AppRoot:OnLoad()
end

function love.update(dt)
    AppRoot:OnUpdate(dt)
end

function love.draw()
    local time = loveTimer.getTime()
    --
    AppRoot:OnRendering()
    --
    spendTimeTips[2] = loveTimer.getTime() - time
    --
    loveGraphics.setColor(1,0,0,1)
    loveGraphics.print(table.concat(spendTimeTips,''),10,0)
    loveGraphics.print(resolutionTips,10,20)
end

do start() end