---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:39
---数学库入口

---@public obj table
---@return string
typeof = function(obj)
    local rawType = type(obj)
    if rawType == 'table' and obj.__type then
        return obj.__type
    else
        return rawType
    end
end

math.clamp = function(value,min,max)
    return math.max(min,math.min(value,max))
end

require('app/mathlib/vector2')
require('app/mathlib/vector3')
require('app/mathlib/vector4')
require('app/mathlib/matrix4x4')