---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:37
---
---@class vector3
---@field x number
---@field y number
---@field z number
local vector3 = {}

vector3.__add = function(a,b)

end

vector3.__sub = function(a,b)

end

---@public
function vector3.new(x,y,z)
    local vec3 = {
        x = x,
        y = y,
        z = z
    }
    setmetatable(vec3,vector3)
    return vec3
end

---@public
---@return number
function vector3.dot()

end

---@public
---@return vector3
function vector3.cross()

end

---@public
---@return vector3
function vector3.normalize()

end

---@type vector3
_G["vector3"] = vector3