---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:28
--- 全局常量声明

SCREEN_WIDTH = 800

SCREEN_HEIGHT = 480

PIXEL_WIDTH = 800

PIXEL_HEIGHT = 480

