---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:28
--- 全局常量声明

SCREEN_WIDTH = 1280

SCREEN_HEIGHT = 720

PIXEL_WIDTH = 427

PIXEL_HEIGHT = 240

--427x240