---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:28
--- 全局常量声明

SCREEN_WIDTH = 1600

SCREEN_HEIGHT = 900

PIXEL_WIDTH = 1280

PIXEL_HEIGHT = 720

--427x240

APP_WORKING_DIR = love.filesystem.getWorkingDirectory()