---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/15 20:05
---程序主入口，以及love2d相关的生命周期回调

require("const")
require("mathlib")

local function start()
    love.window.setTitle("Lua 3d Pipeline")
    love.window.setMode(SCREEN_WIDTH, SCREEN_HEIGHT, {resizable=true, vsync=false})
end

function love.load()

end

function love.update(dt)

end

function love.draw()
    love.graphics.print("hello world!")
end

do start() end