---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/19 9:52
---简易的逐像素BlinnPhong光照模型

local vertexLayoutIdx = VertexLayoutIndex

local vector3 = vector3
local luaMath = math

---@class ShaderTest : Shader
local ShaderTest = declareClass("ShaderTest",classLib.Shader)

function ShaderTest:ctor()

end

---@public
---@param renderer Renderer
function ShaderTest:SetRenderState(renderer)
    renderer:EnableAlphaBlend(false)
end

---@private
---@return VertexShaderOutput
function ShaderTest:VertexShader()
    local worldPos = self:GetVertexDataVec3(vertexLayoutIdx.worldPos)
    local clipPos = self.mvpMatrix * worldPos--将顶点从世界空间换到裁剪空间
    --
    local normal = self:GetVertexDataVec3(VertexLayoutIndex.normal)
    local normalRotate = self:GetMatrix4x4("normalRotateMat")
    normal = normalRotate * normal--旋转法线
    --
    local uv = self:GetVertexDataVec2(vertexLayoutIdx.uv)
    --
    ---@type VertexShaderOutput
    local o = {
        clipPos = clipPos,
        worldPos = worldPos,
        normal = vector3.new(normal.x,normal.y,normal.z),
        uv = uv
    }
    return o
end

---@private
---@param input FragmentShaderInput
---@return number,number,number,number r,g,b,a
function ShaderTest:FragmentShader(input)
    local uv = input.uv
    local albedo = self:SampleTex2d('albedo',uv)
    --
    local lightDir = self:GetVector3('lightDir')
    local inverseLightDir = vector3.normalize(lightDir * -1)
    local lightColor = self:GetColor('lightColor')
    local lightIntensity = self:GetNumber('lightIntensity')
    --
    local normal = vector3.normalize(input.normal)
    --计算漫反射
    local diffuse = vector3.dot(normal,inverseLightDir)
    diffuse = diffuse * 0.5 + 0.5
    local diffuseColor = diffuse * lightColor * lightIntensity
    --计算高光
    local viewPoint = self:GetVector3('viewPoint')
    local viewDir = vector3.normalize(viewPoint - input.worldPos)
    local halfV = vector3.normalize(viewDir + inverseLightDir)
    local gloss = self:GetNumber('gloss')
    local specular = luaMath.pow( luaMath.max(0,vector3.dot(halfV,normal)),gloss)
    local specularColor = lightColor * self:GetColor('specularColor') * specular
    ---计算像素最终颜色
    ---@type Color
    local finalColor = albedo * (diffuseColor + specularColor)
    return finalColor.r,finalColor.g,finalColor.b,1
end

return ShaderTest