---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/20 13:06
---

VertexObjectHelper = {}

VertexObjectHelper.LoadFromPLY = function(filePath)
    local abPath = table.concat({APP_WORKING_DIR,'/',filePath},'')
    local file = io.open(abPath)
    if not file then
        return nil
    end
    local line = file:read()
    local row = 1
    local readingData = false
    local verteicesNumber = 0
    local trianglesNumber = 0
    local verticesDataEndRow = 0
    local trianglesDataEndRow = 0
    --
    local verticesData = {}
    local indicesData = {}
    while line ~= nil do
        if readingData then
            if row < verticesDataEndRow then
                for i = 1,8 do
                    verticesData[#verticesData + 1] = file:read('*n')
                end
            elseif row >= verticesDataEndRow and row < trianglesDataEndRow then
                --读入三角形索引数据。ply格式模型的三角形顶点顺序为逆时针。
                --
                local vertexCnt = file:read('*n')
                if vertexCnt == 3 then--这个面是一个三角形
                    for i = 1,vertexCnt do
                        indicesData[#indicesData + 1] = file:read('*n') + 1
                    end
                elseif vertexCnt == 4 then--这个面是一个矩形
                    --我们需要手动将矩形拆分为两个三角形
                    local vertexIdx = {}
                    for i = 1,vertexCnt do
                        vertexIdx[i] = file:read('*n') + 1
                    end
                    indicesData[#indicesData + 1] = vertexIdx[1]
                    indicesData[#indicesData + 1] = vertexIdx[2]
                    indicesData[#indicesData + 1] = vertexIdx[3]
                    --
                    indicesData[#indicesData + 1] = vertexIdx[1]
                    indicesData[#indicesData + 1] = vertexIdx[3]
                    indicesData[#indicesData + 1] = vertexIdx[4]
                    --三角形总数+1
                    trianglesNumber = trianglesNumber + 1
                end
            end
        else
            local tag,name,data = string.match(line,'(%a+)%s(%a+)%s(%d+)')
            if tag == 'element' then
                if name == 'vertex' then
                    verteicesNumber = tonumber(data)
                elseif name == 'face' then
                    trianglesNumber = tonumber(data)
                end
            end
        end
        --
        line = file:read()
        row = row + 1
        if line == 'end_header' then
            readingData = true
            verticesDataEndRow = row + verteicesNumber
            trianglesDataEndRow = verticesDataEndRow + trianglesNumber
        end
    end
    file:close()
    if verteicesNumber <= 0 or trianglesNumber <= 0 then
        return nil
    end
    ---@type VertexObject
    local vertexObj = classLib.VertexObject.new()
    vertexObj:SetVerticesData(verticesData)
    vertexObj:SetIndicesData(indicesData)
    vertexObj:SetVerticesNumber(verteicesNumber)
    vertexObj:SetTrianglesNumber(trianglesNumber)
    --
    vertexObj:SetLayout(VertexLayoutIndex.worldPos,8,0,3)
    vertexObj:SetLayout(VertexLayoutIndex.normal,8,3,3)
    vertexObj:SetLayout(VertexLayoutIndex.uv,8,6,2)
    return vertexObj
end