---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/16 16:05
---颜色

local setmetatable = setmetatable
local rawget = rawget
local getLuaDataType = type

---@class Color
---@field r number 0~1
---@field g number 0~1
---@field b number 0~1
---@field a number 0~1
---@field red Color
---@field green Color
---@field blue Color
---@field white Color
---@field black Color
---@field yellow Color
---@field cyan Color
---@field magenta Color
---@field gray Color
---@field raywhite Color from RayLib  https://github.com/raysan5/raylib

local Color = {}
local getter = {}

function Color.new(r,g,b,a)
    local color = {
        r = r,
        g = g,
        b = b,
        a = a,
    }
    setmetatable(color,Color)
    return color
end

Color.__index = function(t,k)
    local getFunc = rawget(getter,k)
    if getFunc ~= nil then
        return getFunc(t)
    end
    return nil
end

Color.__add = function(lhs,rhs)
    return Color.new(lhs.r + rhs.r,lhs.g + rhs.g,lhs.b + rhs.b,lhs.a + rhs.a)
end

Color.__sub = function(lhs,rhs)
    return Color.new(lhs.r - rhs.r,lhs.g - rhs.g,lhs.b - rhs.b,lhs.a - rhs.a)
end

Color.__mul = function(lhs,rhs)
    if getLuaDataType(lhs) == 'number' then
        return Color.new(rhs.r * lhs,rhs.g * lhs,rhs.b * lhs,rhs.a * lhs)
    elseif getLuaDataType(rhs) == 'number' then
        return Color.new(lhs.r * rhs,lhs.g * rhs,lhs.b * rhs,lhs.a * rhs)
    else
        return Color.new(lhs.r * rhs.r,lhs.g * rhs.g,lhs.b * rhs.b,lhs.a * rhs.a)
    end
end

Color.__div = function(lhs,rhs)
    if getLuaDataType(lhs) == 'number' then
        return Color.new(rhs.r / lhs,rhs.g / lhs,rhs.b / lhs,rhs.a / lhs)
    elseif getLuaDataType(rhs) == 'number' then
        return Color.new(lhs.r / rhs,lhs.g / rhs,lhs.b / rhs,lhs.a / rhs)
    end
end

Color.__eq = function(lhs,rhs)
    return lhs.a == rhs.a and lhs.g == rhs.g and lhs.b == rhs.b and lhs.a == rhs.a
end

Color.__tostring = function(color)
    local str = table.concat({'Color = (a = ',color.a,' g = ',color.g,' b = ',color.b,' a = ',color.a,' )'},'')
    return str
end

getter.red 	    = function() return Color.new(1,0,0,1) end
getter.green	= function() return Color.new(0,1,0,1) end
getter.blue	    = function() return Color.new(0,0,1,1) end
getter.white	= function() return Color.new(1,1,1,1) end
getter.black	= function() return Color.new(0,0,0,1) end
getter.yellow	= function() return Color.new(1, 0.9215686, 0.01568628, 1) end
getter.cyan	    = function() return Color.new(0,1,1,1) end
getter.magenta	= function() return Color.new(1,0,1,1) end
getter.gray     = function() return Color.new(0.5,0.5,0.5,1) end
--from RayLib  https://github.com/raysan5/raylib
getter.raywhite	= function() return Color.new(0.96, 0.96, 0.96,1) end

setmetatable(Color,Color)

---@type Color
_G["Color"] = Color
