---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/16 15:12
---渲染模块入口

require("render/color")
require("render/vertexobject")
require("render/shader")
require("render/renderer")