---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/16 15:12
---渲染模块入口

require("app/render/color")
require("app/render/vertexobject")
require("app/render/shader")
require("app/render/renderer")
require("app/render/texturemanager")