---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/16 18:09
---着色器基类
---@class Shader
local Shader = declareClass("Shader")

function Shader:ctor()
    ---@type table<string,vector3>
    self.uniformVector3 = {}

    ---@type table<string,matrix4x4>
    self.uniformMatrix4x4 = {}
end

---@protected
function Shader:VertexProgram()

end

---@protected
function Shader:FragmentProgram()

end

---@public
---@param name string
---@param vector3 vector3
function Shader:SetVector3(name,vector3)
    self.uniformVector3[name] = vector3
end

---@public
---@param name string
---@return vector3
function Shader:GetVector3(name)
    local ret = self.uniformVector3[name]
    if ret == nil then
        ret = vector3.zero()
    end
    return ret
end

---@public
---@param name string
---@param matrix4x4 matrix4x4
function Shader:SetMatrix4x4(name,matrix4x4)
    self.uniformMatrix4x4[name] = matrix4x4
end

---@public
---@param name string
---@return matrix4x4
function Shader:GetMatrix4x4(name)
    local ret = self.uniformMatrix4x4[name]
    if ret == nil then
        ret = matrix4x4.identity()
    end
    return ret
end


return Shader