---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2021/11/20 17:47
---

---@class Texture2d
---@field width number
---@field height number
---@field data userdata

local loveImg = love.image

---@class TextureManager
local TextureManager = declareClass("TextureManager")

function TextureManager:ctor()

    ---@type table<number,Texture2d>
    self.texDataDict = {}
end

function TextureManager:Init()

end

function TextureManager:UnInit()

end

---@public
---@return Texture2d,number
function TextureManager:LoadTexture(texFilePath)
    local texId = 0
    for i = 1,100 do
        if not self.texDataDict[i] then
            texId = i
            break
        end
    end
    if texId <= 0 then
        return 0
    end
    ---@type Texture2d
    local tex2d = nil
    local texData = loveImg.newImageData(texFilePath)
    if texData then
        tex2d = {
            width = texData:getWidth(),
            height = texData:getHeight(),
            data = texData,
        }
        self.texDataDict[texId] = tex2d
    else
        texId = 0
    end
    return texId,tex2d
end

---@public
function TextureManager:ReleaseTexture(texture2dId)
    local tex2d = self.texDataDict[texture2dId]
    if tex2d then
        tex2d.data:release()
        self.texDataDict[texture2dId] = nil
        return true
    end
    return false
end

---@public
---@param texture2dId number
---@return Texture2d
function TextureManager:GetTexture2d(texture2dId)
    return self.texDataDict[texture2dId]
end

---@public
---@return number,number,number,number
function TextureManager:SampleTexture2d(texture2dId,uv)
    local texture2d = self.texDataDict[texture2dId]
    local r,g,b,a = 0,0,0,1
    if texture2d then
        local w = texture2d.width - 1
        local h = texture2d.height - 1
        local uvX = math.min(uv.x,1)
        local uvY = 1 - math.min(uv.y,1)
        r,g,b,a = texture2d.data:getPixel(w * uvX,h * uvY)
    end
    return r,g,b,a
end

return TextureManager